/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge30;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String, Integer> studentsGrades = new HashTable<>();
        studentsGrades.add("John", 99);
        studentsGrades.add("Liam", 92);
        studentsGrades.add("Tara", 100);
        studentsGrades.add("Miral", 91);
        studentsGrades.add("Adam", 88);
        studentsGrades.add("Elina", 95);
        studentsGrades.add("Tia", 90);

        System.out.println("The size is => " + studentsGrades.getSize());
        System.out.println(studentsGrades.get("Tara"));
        System.out.println("Remove Miral => " + studentsGrades.remove("Miral"));
        System.out.println("The size is => " + studentsGrades.getSize());
        System.out.println(studentsGrades.contains("Sara"));
        System.out.println(studentsGrades.contains("Liam"));
        System.out.println(studentsGrades.hashCode("Adam"));

    }
}
