/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        BinarySearchTree <Integer> binaryTree = new BinarySearchTree<>();
        binaryTree.add(8);
        binaryTree.add(3);
        binaryTree.add(10);
        binaryTree.add(14);
        binaryTree.add(6);
        binaryTree.add(1);
        binaryTree.add(13);
        binaryTree.add(7);
        binaryTree.add(4);

        binaryTree.toString();
//        System.out.println(binaryTree.contains(2));
//        System.out.println(binaryTree.contains(10));
        System.out.println("sum => "+binaryTree.findSum());
        System.out.println(binaryTree.postOrderList);

        BinarySearchTree<Integer> binaryTree1 = new BinarySearchTree<>();
        binaryTree1.setRoot(new BinaryNode<>(1));
        binaryTree1.getRoot().setLeftNode(new BinaryNode<>(5));
        binaryTree1.getRoot().getLeftNode().setLeftNode(new BinaryNode<>(2));
        binaryTree1.getRoot().getLeftNode().setRightNode(new BinaryNode<>(10));
        binaryTree1.getRoot().setRightNode(new BinaryNode<>(3));
        binaryTree1.getRoot().getRightNode().setLeftNode(new BinaryNode<>(13));
        binaryTree1.getRoot().getRightNode().setRightNode(new BinaryNode<>(50));

        System.out.println("max value => "+binaryTree1.findMaxvalue());
        System.out.println(binaryTree1.breadthFirst(binaryTree1));

    }
}
