/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge15;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

//        BinarySearchTree <Integer> binaryTree = new BinarySearchTree<>();
//        binaryTree.add(1);
//        binaryTree.add(5);
//        binaryTree.add(2);
//        binaryTree.add(7);
//        binaryTree.add(0);
//        binaryTree.postOrderTraversal();
//        binaryTree.toString();
//        System.out.println(binaryTree.contains(2));
//        System.out.println(binaryTree.contains(10));

        BinarySearchTree<Integer> binaryTree1 = new BinarySearchTree<>();
        binaryTree1.setRoot(new BinaryNode<>(1));
        binaryTree1.getRoot().setLeftNode(new BinaryNode<>(5));
        binaryTree1.getRoot().getLeftNode().setLeftNode(new BinaryNode<>(2));
        binaryTree1.getRoot().getLeftNode().setRightNode(new BinaryNode<>(10));
        binaryTree1.getRoot().setRightNode(new BinaryNode<>(3));
        binaryTree1.getRoot().getRightNode().setLeftNode(new BinaryNode<>(13));
        binaryTree1.getRoot().getRightNode().setRightNode(new BinaryNode<>(11));



        System.out.println(binaryTree1.findMaxvalue());
        System.out.println(binaryTree1.breadthFirst(binaryTree1));

    }
}
