/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class Main {
    public static void main (String [] args){

        System.out.println("*************************Start*************************");
        LinkedList linkedList = new LinkedList();

        linkedList.insert("A");
//        linkedList.insert("B");

        System.out.println(linkedList);
        System.out.println(linkedList.isIncluded("B"));

    }


}
