/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class Main {
    public static void main (String [] args){

        System.out.println("*************************Start*************************");
        LinkedList linkedList = new LinkedList();

        linkedList.insert("a");
        linkedList.insert("b");
        linkedList.insert("c");
        linkedList.insert("d");
        System.out.println(linkedList);
        System.out.println(linkedList.isIncluded("g"));
        System.out.println(linkedList.size);
        System.out.println("*************************End***************************");

    }


}
