/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge30;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    //   " CHALLENGE 30 "

    @Test
        public void hashTableMethodsTest(){

        HashTable<String, Integer> studentsGrades = new HashTable<>();

        assertTrue(studentsGrades.isEmpty());

        studentsGrades.add("Tara",100);
        assertEquals(1,studentsGrades.getSize());

        studentsGrades.add("Liam", 88);
        assertEquals(2,studentsGrades.getSize());
        assertFalse(studentsGrades.isEmpty());

        studentsGrades.hashCode("Tara");
        assertEquals(2599292, studentsGrades.hashCode("Tara"));

        studentsGrades.remove("Liam");
        assertEquals(1,studentsGrades.getSize());

        assertTrue(studentsGrades.contains("Tara"));
        assertFalse(studentsGrades.contains("John"));

        studentsGrades.get("Sara");
        assertEquals(null, studentsGrades.get("Sara"));

        studentsGrades.remove("Tara");
        assertTrue(studentsGrades.isEmpty());



    }
}
